name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: valesordev/ui/.github/workflows/astro-pages.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
